fasta               : 'resources/sequence.fa'
gff                 : 'resources/annotation.gff'
input               : 'design.csv'
# Trimming
trimmer             : fastp
extra_fastp_args    : '--detect_adapter_for_pe --trim_poly_x --trim_poly_g --poly_g_min_len=5 --poly_x_min_len=5'
# Pre-mapping
premap_star_index   : 'resources/STAR-premap-index'
premap_exclude_bed  : 'resources/pre-mapping.bed'
save_premapped      : true
# STAR
star_index          : 'resources/STAR-index'
save_unaligned      : true
# Salmon
salmon_index        : 'resources/Salmon-index'
# BigWig
skip_bigwig         : false
bigwig_tool         : 'deeptools'
# Irrelevant qc
skip_dupradar       : true
skip_qualimap       : true
skip_biotype_qc     : true
skip_stringtie      : true
# Save-to
save_reference      : false
publish_dir_mode    : 'link'
outdir              : results
# Resources
max_memory          : '1024.GB'
max_cpus            : 128
max_time            : '240.h'
